# Generated by Django 5.0.7 on 2024-07-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_variations'),
        ('orders', '0004_remove_orderproduct_variations'),
        ('store', '0005_auto_20240710_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
